<?php

namespace mondrakeNG\mm\core;

/**
 * mondrake diagnostic class. Handles all diagnostic messages generated by mondrake core functions.
 */
class MMDiagMsg
{
    var $severity;
    var $className;
    var $id;
    var $fullText;
    var $text;
    var $time;
    var $uTime;
    var $elapsed;
    var $params = [];
}
